### PR TITLE
Example cred download

### PR DESCRIPTION
**Pull request by ahayden**
I'm not entirely sure this works, but could be a simple way to make STS creds available locally... This example is for discussion at the moment.

### CODE REVIEW

**Comment by zaro0508** [comment]
interesting idea, however it doesn't seem very user friendly.  Instead how about we host a page at `/creds` endpoint with a `Get STS` button?  when pressed the STS creds appear on the page?  The page could even take `session timeout` as a parameter.

**Comment by ahayden** [comment]
That would definitely be more friendly... I wonder if it would be good to different access to sts download by team as well. We don't have a way to nest teams, but we could have an sts-allowed team within the hierarchy. We could also have an entirely separate app for this.

**Comment by tthyer** [comment]
It would be interesting to see whether this works but I think Khai's endpoint idea is probably simpler and a little more user friendly.

**Review by brucehoff — CHANGES_REQUESTED** [review]
As we discussed I suggest making such a change not to the login app' itself but in a clone of this repo', which you can then run in a dev' account or on your own lap top.  You would remove from the app' the bit that redirects to Service Catalog.  (To run on your laptop you'd configure your Synapse OAuth client to redirect to 127.0.0.1.  I can give more guidance, as needed.)

**Comment by brucehoff** [comment]
Please see my comment above.  I recommend *not* merging this PR.

**Pull request closed without merging**
